module.exports = {
  CUSTOMER_LOGGED_OUT_SUCCESSFULLY: "Customer loggedout successfully",
  OTP_ALREADY_SENT_TO_PROVIDED_PHONE_NUMBER: "Otp already send to the provided phonenumber",
  REPORT_UPDATED_SUCCESSFULLY: "Report updated successfully",
  CUSTOMER_APPS_NOT_EXIST: "Customer apps not exist",
  REPORT_CREATED_SUCCESSFULLY: "Report created successfully",
  TIMELINES_FETCHED_SUCCESSFULLY: "Timelines fetched successfully",
  TIMELINE_FETCHED_SUCCESSFULLY: "Timeline fetched successfully",
  TIMELINE_CREATED_SUCCESSFULLY: "Timeline created successfully",
  REPORT_NOT_EXIST: "Report not exist",
  REPORT_FETCHED_SUCCESSFULLY: "Report fetched successfully",
  REPORT_CREATED_SUCCESSFULLY: "Report created successfully",
  CUSTOMER_APP_NOT_EXIST: "Customer App not exist",
  REPORTS_FETCHED_SUCCESSFULLY: "Reports fetched successfully",
  REPORT_SEND_SUCCESSFULLY: "Report send successfully",
  REASON_NOT_EXIST: "Reason not exist",
  REASON_FETCHED_SUCCESSFULLY: "Reason fetched successfully",
  REASONS_FETCHED_SUCCESSFULLY: "Reasons fetched successfully",
  REASON_CREATED_SUCCESSFULLY: "Reason created successfully",
  OTP_ALREADY_SENT: "Otp already sent",
  APP_UPDATED_SUCCESSFULLY: "App updated successfully",
  APP_FETCHED_SUCCESSFULLY: "App fetched successfully",
  OTP_ALREADY_SENT_TO_PROVIDED_EMAIL: "Otp already sent to provided email",
  INCORRECT_EMAIL_ADDRESS: "Incorrect Email Address",
  INCORRECT_OTP: "Incorrect Otp",
  OTP_EXPIRED: "Otp expired",
  PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully",
  PROFILE_FETCHED_SUCCESSFULLY: "Profile fetched successfully",
  ADMIN_LOGGED_OUT_SUCCESSFULLY: "Admin logged out successfully",
  APP_NOT_EXIST: "App not exist",
  CUSTOMER_APPS_FETCHED_SUCCESSFULLY: "Customer apps fetched successfully",
  CUSTOMER_APP_FETCHED_SUCCESSFULLY: "Customer app fetched successfully",
  CUSTOMER_APP_ADDED_SUCCESSFULLY: "Customer app added successfully",
  CUSTOMER_CREATED_SUCCESSFULLY: "Customer created successfully",
  NEWS_FETCHED_SUCCESSFULLY: "News fetched successfully",
  NEWS_CREATED_SUCCESSFULLY: "News created successfully",
  APPS_FETCHED_SUCCESSFULLY: "Apps fetched successfully",
  APP_CREATED_SUCCESSFULLY: "App created successfully",
  ADMIN_LOGGED_IN_SUCCESSFULLY: "Admin loggedin successfully",
  REQUEST_SENT_SUCCESSFULLY: "Request sent successfully",
  REQUESTS_FETCHED_SUCCESSFULLY: "Requests fetched successfully",
  REQUEST_FETCHED_SUCCESSFULLY: "Request fetched successfully",
  REQUEST_UPDATED_SUCCESSFULLY: "Request updated successfully",
  APP_CREATED_SUCCESSFULLY: "App created successfully",
  APPS_FETCHED_SUCCESSFULLY: "Apps fetched successfully",
  APP_FETCHED_SUCCESSFULLY: "App fetched successfully",
  EMAIL_ALREADY_ASSOCIATED_WITH_ANOTHER_ACCOUNT: "Email already associated with another account",
  PHONE_NUMBER_ALREADY_ASSOCIATED_WITH_ANOTHER_ACCOUNT: "Phone number already associated with another account",
  CUSTOMER_REGISTERED_SUCCESSFULLY: "Customer registered successfully",
  OTP_VERIFIED_SUCCESSFULLY: "Otp verified successfully",
  UNABLE_TO_VERIFY_OTP: "Unable to verify otp",
  CUSTOMER_NOT_EXIST: "Customer not exist",
  OTP_ALREADY_SENT_TO_CUSTOMER_EMAIL: "Otp already sent to customer email",
  OTP_SENT_SUCCESSFULLY: "Otp sent successfully",
  CUSTOMERS_FETCHED_SUCCESSFULLY: "Customers fetched successfully",
  NO_ANY_CUSTOMER_FOUND: "No any customer found",
  CUSTOMER_UPDATED_SUCCESSFULLY: "Customer updated successfully",
  CUSTOMER_DELETED_SUCCESSFULLY: "Customer deleted successfully",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully",
  PASSWORD_CHANGE_SUCCESSFULLY: "Password change successfully",
  PASSWORD_NOT_MATCH: "Password not match",
  CUSTOMER_FETCHED_SUCCESSFULLY: "Customerfetched successfully",
  INVALID_CREDENTIALS: "Invalid credentials",
  CUSTOMER_LOGGED_IN_SUCCESSFULLY: "Customer logged in successfully",
  DELIVERY_ADDRESS_SAVED_SUCCESSFULLY: "Delivery address saved successfully",
  CUSTOMER_PROFILE_ALREADY_COMPLETED: "Customer profile already completed",
  CUSTOMER_IS_BLOCKED_BY_ADMIN: "Customer is blocked by admin",
  DRIVER_NOT_EXIST: "Driver not exist",
  DRIVER_REGISTERED_SUCCESSFULLY: "Driver registered successfully",
  NO_ANY_DRIVER_FOUND: "No any driver found",
  DRIVERS_FETCHED_SUCCESSFULLY: "Drivers fetched successfully",
  DRIVER_DELETED_SUCCESSFULLY: "Driver deleted successfully",
  DRIVER_UPDATED_SUCCESSFULLY: "Driver updated successfully",
  DRIVER_IS_BLOCKED_BY_ADMIN: "Driver is blocked by admin",
  DRIVER_LOGGED_IN_SUCCESSFULLY: "Driver logged in successfully",
  OTP_ALREADY_SENT_TO_DRIVER_EMAIL: "Otp already sent to driver email",
  DRIVER_PROFILE_ALREADY_COMPLETED: "Driver profile already completed",
  CUSTOMER_LOGOUT_SUCCESSFULLY: "Customer logout successfully",
  DRIVER_LOGOUT_SUCCESSFULLY: "Driver logout successfully",
  ADMIN_LOGOUT_SUCCESSFULLY: "Admin logout successfully",
  ADMIN_REGISTERED_SUCCESSFULLY: "Admin registered successfully",
  ADMIN_NOT_EXIST: "Admin not exist",
  FUEL_CATEGORY_ALREADY_EXIST: "Fuel category already exist",
  FUEL_CATEGORY_SAVED_SUCCESSFULLY: "Fuel category saved successfully",
  FUEL_CATEGORY_FETCHED_SUCCESSFULLY: "Fuel category fetched successfully",
  DELIVERY_ADDRESSES_FETCHED_SUCCESSFULLY: "Delivery addresses fetched successfully",
  FUEL_CATEGORIES_FETCHED_SUCCESSFULLY: "Fuel categories fetched successfully",
  HOME_DATA_FETCHED_SUCCESSFULLY: "Home data fetched successfully",
  OLD_PASSWORD_IS_INCORRECT: "Old password is incorrect",
  BANKS_FETCHED_SUCCESSFULLY: "Banks fetched successfully",
  FUEL_PRODUCT_SAVED_SUCCESSFULLY: "Fuel product saved successfully",
  FUEL_PRODUCTS_FETCHED_SUCCESSFULLY: "Fuel products fetched successfully",
  CAPACITIES_FETCHED_SUCCESSFULLY: "Capacities fetched successfully",
  ADMIN_LOGIN_SUCCESS_MSG: "Admin Log In Success !",
  PROFILE_UPDATED: "Profile Updated !!",
  DELIVERY_ADDRESS_NOT_EXIST: "Delivery address not exist",
  DELIVERY_ADDRESSES_DELETED_SUCCESSFULLY: "Delivery addresses deleted successfully",
  FUEL_CATEGORY_DELETED_SUCCESSFULLY: "Fuel category deleted successfully",
  FUEL_CATEGORY_UPDATED_SUCCESSFULLY: "Fuel category updated successfully",
  FUEL_PRODUCTS_UPDATED_SUCCESSFULLY: "Fuelproducts updated successfully",
  DELIVERY_ADDRESSES_UPDATED_SUCCESSFULLY: "Delivery addresses updated successfully",
  FUEL_PRODUCTS_DELETED_SUCCESSFULLY: "Fuel products deleted successfully",
  FUEL_PRODUCT_UPDATED_SUCCESSFULLY: "Fuel product updated successfully",
  FORM_ADDED_SUCCESSFULLY: "Form added successfully",
  FORMS_FETCHED_SUCCESSFULLY: "Forms fetched successfully",
  BOOKING_FETCHED_SSUCESSFULLY: "Booking fetched sucessfully",
  BOOKING_DELETED_SUCCESSFULLY: "Booking deleted sucessfully",
  BOOKING_NOT_EXIST: "Booking not exist",
  BOOKING_NOT_DELIVERED: "Booking not delivered",
  FORM_UPDATED_SUCCESSFULLY: "Form updated successfully",
  MESSAGE_SENT_SUCCESSFULLY: "Message sent successfully",
  BOOKING_ADDED_SUCCESSFULLY: "Booking added successfully",
  NO_BOOKING_FOUND: "No booking found",
  BOOKING_ASSIGNED_SUCCESSFULLY: "Booking assigned successfully",
  BOOKING_UPDATED_SUCCESSFULLY: "Booking updated successfully",
  INVALID: "Invalid Operation",
  INVALID_PROMO: "Invalid Promo",
  ON_BREAK: "Driver is on Break",
  ADD_REVIEW_SUCCESS: "Add review success",
  PAST_OR_ONGOING_ERR: "Type Is Required !, Ongoing Or Past.",
  NO_BOOKING: "No booking",
  NO_REVIEW_FOUND: "No review found",
  DASHBOARD_FETCHED_SUCCESSFULLY: "Dashboard fetched successfully",
  BOOKING_CANCELLED_SUCCESSFULLY: "Booking cancelled successfully",
  NO_CARD_FOUND: "No card found",
  CARD_SAVED_SUCCESSFULLY: "Card saved successfully",
  CARDS_FETCHED_SUCCESSFULLY: "Cards fetched successfully",
  CARDS_UPDATED_SUCCESSFULLY: "Cards updated successfully",
  CARD_DELETED_SUCCESSFULLY: "Card deleted successfully",
  SUCCESSFULLY_ADDED_TO_WALLET: "Wallet updated sucessfully",
  TRANSACTIONS_FETCHED_SUCCESSFULLY: "Transactions fetched successfully",
  DATA_FETCHED_SUCCESSFULLY: " Data fetched successfully",
  NO_TRANSACTIONS_TILL_NOW: "No transactions till now",
  PROMO_CODE_ADDED_SUCCESSFULLY: "Promo code added successfully",
  PROMOS_FETCHED_SUCCESSFULLY: "Promos fetched successfully",
  PROMO_CODE_EXPIRE: "This Promo code already expired",
  NO_SLOT_FOUND: "No slot found !",
  SLOT_FETCHED_SUCCESSFULLY: "Slot fetched successfully",
  SLOT_UPDATED: "Slot Updated",
  DAY_REQ: "Day is required !",
  DELETE_VEHICLE_SUCCESSFULLY: "Delete Vehicle Successfully",
  DELETE_VEHICLE_CATAGORY: "Delete Vehicle Category Successfully",
  ADMIN_UPDATED_SUCCESSFULLY: "Admin Update Successfully",
  VEHICLE_CATEGORY_FETCHED: "Vehicle Category Fetched Successfully",
  ADMIN_FETCH_SUCCESSFULLY: "Admin Fetch Successfully",
  VEHICLE_FETCHED_SUCCESSFULLY: "Vehicle Fetched Successfully",
  NOT_FOUND: "Not Found !",
  No_FUEL_PRODUCT_ADDED_BY_ADMIN: "No Fuel Category added by admin till now",
};
